baseurl: "/"
languageCode: "fr-FR"
title: "c11e"
theme: ["c11e", "reveal-hugo"]
defaultContentLanguage: "fr"
defaultContentLang: "fr"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"
mainsections: ["articles"]
minify:
  disableXML: true
  minifyOutput: true
permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: À propos
      url: "/a-propos/"
      weight: 3
    - name: Mes livres
      url: "https://cyrilvallee.com/livres/"
      weight: 2
    - name: Lectures
      url: "/lectures/"
    - name: RSS
      url: "index.xml"

params:
  description: "c11e est un blog de l'écrivain Cyril Vallée | c11e is a blog of writer Cyril Vallée"
  footer: "[c11e](/)  - {Year} | [Github](https://github.com/crlvll) | [Mastodon](https://tooting.ch/@arveed) | [Bluesky](https://bsky.app/profile/arveed.bsky.social) | [Archives](/archives/)"
  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"
  label:
    text: ""
    icon: /images/C11Ew.png
    iconHeight: 100

  ShowReadingTime: true
  ShowWordCount: true

taxonomies:
  category: categories
  tag: tags

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

outputFormats:
  Reveal:
    baseName: index
    mediaType: text/html
    isHTML: true
